export { common } from './common'
export { welcome } from './welcome'
export { home } from './home'
export { profile } from './profile'
export { skillNames } from './skills'
export { screenTitles } from './screens'
export { resolveCopy, type Copy } from './types'
export { tv, TREATMENT } from './treatment'
export { picker, platformDetail, simulator } from './simulator'
export { platforms, getPlatform, type Platform, type PlatformCategory } from './platforms'
